### ISSUE TITLE
Add entry to equipment log

### ISSUE THREAD

**Issue by karthikrao5** [karthikrao5/InventoryManagement#10]
an IT administrator, I want to add an equipment log entry so that I can update the equipment history. (IT admin #6)

**Comment by ghost** [comment]
- [x] Define database document structures and control flow.

- [x] Write a skeleton for the database class.

- [x] Write a skeleton for the data validator class.

- [x] Write a skeleton for the data layer access service class using database class and data validator class. This class will be the service that backend REST API endpoints will be using.

- [x] Write a script to populate db contents.

- [ ] Finish database function for add (this shouldn't have much business logic).

- [ ] Finish data validation function for add (this is where business logic lives).

- [ ] Finish database service function for add (simple function that accepts the array or equipment object and return a tuple containing (success/fail and internal id).

- [ ] Add logs to db script and add more data.

- [ ] //TODO: front-end - Andres

- [ ] //TODO: middle-ware - Karthik

**Comment by ghost** [comment]
Use stories/add-entry-to-equipment-log-10 branch for development.
